language: node_js
node_js:
  - lts/*
  - node

stages:
  - test
  - release

jobs:
  include:
    - stage: release
      node_js: node
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|react-16|react-17)$
