language: node_js
node_js:
  - lts/*
  - node

stages:
  - test
  - name: release
    if: branch IN (master, react-16, react-17) && type != pull_request

jobs:
  include:
    - stage: release
      node_js: node
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
